# Copyright 2023 Uber Technologies, Inc.
# Licensed under the Apache License, Version 2.0

load("@bazel-zig-cc//toolchain/platform:defs.bzl", "declare_libc_aware_platforms")

package(
    default_visibility = ["//visibility:public"],
)

declare_libc_aware_platforms()
