# Copyright 2023 Uber Technologies, Inc.
# Licensed under the MIT License

load("@hermetic_cc_toolchain//toolchain/platform:defs.bzl", "declare_libc_aware_platforms")

package(
    default_visibility = ["//visibility:public"],
)

declare_libc_aware_platforms()
