# Copyright 2023 Uber Technologies, Inc.
# Licensed under the MIT License

# The commands are in a single line due to this warning in buildkite:
# ⚠️  The command received has multiple lines.
# ⚠️  The Docker Plugin may not correctly run multiple commands in the step-level configuration.
# ⚠️  You will need to use a single command, a script or the plugin's command option.

steps:
  - label: "Test"
    command: ci/test
  - label: "Lint"
    command: ci/lint
  - label: "List Platforms"
    command: ci/list_toolchains_platforms
  - label: "Test Release"
    command: ci/prepare_git && echo "--- ci/release" && ci/release
  - label: "Test zig utilities"
    command: ci/zig-utils
    env:
      HERMETIC_CC_TOOLCHAIN_SKIP_WINE: 1
  - label: "Test rules_cc example"
    command: ci/prepare_git && ci/test_example rules_cc override_repository
  - label: "Test bzlmod example"
    command: ci/prepare_git && ci/test_example bzlmod override_module
  - label: "mod-tidy and update-repos"
    command: tools/mod-tidy && git diff --exit-code
agents:
    - "queue=init"
    - "docker=*"
