# Copyright 2023 Uber Technologies, Inc.
# Licensed under the MIT License

# The commands are in a single line due to this warning in buildkite:
# ⚠️  The command received has multiple lines.
# ⚠️  The Docker Plugin may not correctly run multiple commands in the step-level configuration.
# ⚠️  You will need to use a single command, a script or the plugin's command option.

steps:
  - label: "Test"
    command: ci/test
  - label: "Lint"
    command: ci/lint
  - label: "List Platforms"
    command: ci/list_toolchains_platforms
  - label: "Test Release"
    command: ci/prepare_git && echo "--- ci/release" && ci/release
  # TODO(#99) re-enable
  # - label: "Test zig utilities"
  #   plugins:
  #     - docker#v5.7.0:
  #         image: "debian:stable"
  #   command: apt-get update && apt-get install --no-install-recommends -y wine64 python3 ca-certificates && ci/zig-utils
  - label: "Test rules_cc example"
    command: ci/prepare_git && ci/test_example rules_cc
  - label: "mod-tidy and update-repos"
    command: tools/mod-tidy && git diff --exit-code
agents:
    - "queue=init"
    - "docker=*"
