constraint_setting(name = "libc")

constraint_value(
    name = "glibc_2_28",
    constraint_setting = ":libc",
)

constraint_value(
    name = "musl",
    constraint_setting = ":libc",
)

#constraint_value(
#    name = "glibc_2_19",
#    constraint_setting = ":libc",
#)
