#!/usr/bin/env bash
set -xeuo pipefail

ZIG=${ZIG:-$(bazel run --run_under=echo @zig_sdk//:zig)}

for target in \
    aarch64-linux-gnu.2.19 \
    aarch64-macos-none \
    x86_64-linux-gnu.2.19 \
    x86_64-macos-none \
    x86_64-windows-gnu
do
    $ZIG build-exe -fno-emit-bin -target $target toolchain/launcher.zig
done

# until bazel-zig-cc gets a zig toolchain, run launcher's unit tests here.
$ZIG test toolchain/launcher.zig

# ReleaseSafe because of https://github.com/ziglang/zig/issues/14036
$ZIG test \
    -OReleaseSafe \
    -target x86_64-windows-gnu \
    --test-cmd wine64-stable \
    --test-cmd-bin \
    toolchain/launcher.zig
