#!/usr/bin/env bash

# Copyright 2023 Uber Technologies, Inc.
# Licensed under the MIT License

set -xeuo pipefail

cd "$(git rev-parse --show-toplevel)"

>&2 echo "--- releaser :flag-lv:"
TAG=$(git tag | tail -1)
tools/bazel run //tools/releaser -- -tag "$TAG" -skipBranchCheck

>&2 echo "--- git diff :git:"
git diff --exit-code

>&2 echo "OK :white_check_mark:"
