#!/usr/bin/env bash

# Copyright 2023 Uber Technologies, Inc.
# Licensed under the MIT License

set -xeuo pipefail

example=$1

echo --- setup "$example"
root=$(git rev-parse --show-toplevel)
cd "examples/$example"

echo --- "testing examples/$example with hermetic_cc_toolchain pointing to git repository root"
"$root/tools/bazel" test "--override_repository=hermetic_cc_toolchain=$root" --test_output=errors ...

echo --- "testing examples/$example with hermetic_cc_toolchain pointing to a directory produced by release tarball"
# generate release tarball and put to temp
REL=$(mktemp -d); trap 'rm -fr $REL' EXIT; "$root/ci/release_v99"
tar -vx -C "$REL" -f "$root/hermetic_cc_toolchain-v99.0.0.tar.gz"

"$root/tools/bazel" test "--override_repository=hermetic_cc_toolchain=$REL" --test_output=errors ...

echo --- "testing examples/$example as is"
"$root/tools/bazel" test --test_output=errors ...
