#!/usr/bin/env bash

# Copyright 2023 Uber Technologies, Inc.
# Licensed under the MIT License

set -xeuo pipefail

example=$1
override_option_name=$2

echo --- setup "$example"
root=$(git rev-parse --show-toplevel)
cd "examples/$example"

echo --- "testing examples/$example with hermetic_cc_toolchain pointing to git repository root"
# lockfile_mode=off, so examples/$example/MODULE.bazel.lock does not get the override below
"$root/tools/bazel" test --lockfile_mode=off "--$override_option_name=hermetic_cc_toolchain=$root" --test_output=errors ...

echo --- "testing examples/$example with hermetic_cc_toolchain pointing to a directory produced by release tarball"
# generate release tarball and put to temp
REL=$(mktemp -d); trap 'rm -fr $REL' EXIT; "$root/ci/release_v99"
tar -vxf "../../hermetic_cc_toolchain-v99.0.0.tar.gz" -C "$REL"

# lockfile_mode=off, so examples/$example/MODULE.bazel.lock does not get the override below
"$root/tools/bazel" test --lockfile_mode=off "--$override_option_name=hermetic_cc_toolchain=$REL" --test_output=errors ...

echo --- "testing examples/$example as is"
"$root/tools/bazel" test --test_output=errors ...
