#!/usr/bin/env bash

# Copyright 2023 Uber Technologies, Inc.
# Licensed under the MIT License

set -xeuo pipefail

echo "--- which zig"
ZIG=${ZIG:-$(tools/bazel run "$@" --run_under=echo @zig_sdk//:zig)}

for zigfile in $(git ls-files '*.zig'); do
    echo "--- compile $zigfile for various architectures"
    for target in \
        aarch64-linux-gnu.2.28 \
        aarch64-macos-none \
        x86_64-linux-gnu.2.28 \
        x86_64-macos-none \
        x86_64-windows-gnu
    do
        if [[ $target == aarch64-macos-none ]]; then
            mcpu=apple_a14
        else
            mcpu=baseline
        fi
        $ZIG build-exe -fno-emit-bin -target $target -mcpu=$mcpu "$zigfile"
    done


    # until hermetic_cc_toolchain gets a zig toolchain, run zig programs' unit tests here.
    echo "--- zig test $zigfile"
    $ZIG test "$zigfile"

    # as of 2023-10 yours truly (@motiejus) was not able to install wine64
    # on CI. See the commit message for details.
    if [[ -z "${HERMETIC_CC_TOOLCHAIN_SKIP_WINE:-}" ]]; then
        echo "--- test $zigfile via wine64"
        $ZIG test \
            -target x86_64-windows-gnu \
            --test-cmd wine64-stable \
            --test-cmd-bin \
            "$zigfile"
    fi
done
