#!/bin/sh

# Copyright 2023 Uber Technologies, Inc.
# Licensed under the MIT License

set -xeu

exec "$(git rev-parse --show-toplevel)/tools/bazel" run @com_github_bazelbuild_buildtools//buildifier -- "$@"
