#!/bin/sh

# Copyright 2023 Uber Technologies, Inc.
# Licensed under the MIT License
set -xeu

cd "$(git rev-parse --show-toplevel)"
echo "--- go mod tidy"
tools/bazel run @rules_go//go -- mod tidy "$@"
