# Copyright 2023 Uber Technologies, Inc.
# Licensed under the MIT License
load("//rules:zig_binary.bzl", "zig_binary")

package(
    default_visibility = ["//test:__pkg__"],
)

zig_binary(
    name = "cp",
    src = "cp.zig",
    visibility = ["//visibility:public"],
)
