---
name: ci
on:
  push:
  pull_request:
defaults:
  run:
    shell: bash
concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

jobs:

  build-and-test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true

      - uses: actions/cache@v4
        name: "Windows: cache bazelisk and zig-cache"
        if: runner.os == 'Windows'
        with:
          key: cache-${{ runner.os }}-${{ hashFiles('.bazelversion', 'toolchain/private/zig_sdk.bzl', '.github/workflows/ci.yaml') }}
          restore-keys: cache-${{ runner.os }}-
          path: |
            C:\Temp\zig-cache
            ~\AppData\Local\bazelisk

      - uses: actions/cache@v4
        name: "MacOS: cache bazelisk and zig-cache"
        if: runner.os == 'macOS'
        with:
          key: cache-${{ runner.os }}-${{ hashFiles('.bazelversion', 'toolchain/private/zig_sdk.bzl', '.github/workflows/ci.yaml') }}
          restore-keys: cache-${{ runner.os }}-
          path: |
            /var/tmp/zig-cache
            ~/Library/Caches/bazelisk

      - uses: actions/cache@v4
        name: "Linux: cache bazelisk and zig-cache"
        if: runner.os == 'Linux'
        with:
          key: cache-${{ runner.os }}-${{ hashFiles('.bazelversion', 'toolchain/private/zig_sdk.bzl', '.github/workflows/ci.yaml') }}
          restore-keys: cache-${{ runner.os }}-
          path: |
            /tmp/zig-cache
            ~/.cache/bazelisk

      - run: echo "common --announce_rc" >> .bazelrc.ci

      - run: ci/list_toolchains_platforms
      - run: tools/bazel test //...
        if: runner.os != 'Windows'
      - run: tools/bazel test //test/c:test_libc_windows_amd64 //test/cgo:cgo_test //test/cgo:cgo_windows_amd64 //test/cgo:cgo_windows_arm64
        if: runner.os == 'Windows'
      - run: ci/zig-utils
        if: runner.os != 'Windows'

      - run: tools/bazel test --config=macos_toolchains --@rules_go//go/config:static --@rules_go//go/config:pure //test/c/...
        if: runner.os == 'macOS'

  test-examples:
    strategy:
      matrix:
        example:
          - {name: rules_cc, override: override_module}
          - {name: bzlmod, override: override_module}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true

      - uses: actions/cache@v4
        name: "Linux: cache bazelisk and zig-cache"
        with:
          key: cache-${{ runner.os }}-${{ hashFiles('.bazelversion', 'toolchain/private/zig_sdk.bzl', '.github/workflows/ci.yaml') }}
          restore-keys: cache-${{ runner.os }}-
          path: |
            /tmp/zig-cache
            ~/.cache/bazelisk

      - run: echo "common --announce_rc" >> .bazelrc.ci

      - run: ci/prepare_git && ci/test_example ${{ matrix.example.name }} ${{ matrix.example.override }}

  lint-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/cache@v4
        name: "Linux: cache bazelisk and zig-cache"
        with:
          key: cache-${{ runner.os }}-${{ hashFiles('.bazelversion', 'toolchain/private/zig_sdk.bzl', '.github/workflows/ci.yaml') }}
          restore-keys: cache-${{ runner.os }}-
          path: |
            /tmp/zig-cache
            ~/.cache/bazelisk

      - run: echo "common --announce_rc" >> .bazelrc.ci

      - run: ci/lint
      - run: ci/release
